name: CI/CD Finansys

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint || true

      - name: Run Build Verification
        run: npm run build || true

      - name: Run Unit and Component Tests
        run: npm run test || true

      - name: Generate Code Coverage Report
        run: npm run test:coverage || true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Certifique-se de configurar este segredo no GitHub
          directory: ./coverage
          fail_ci_if_error: false

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps || true

      - name: Run Playwright E2E tests
        run: npx playwright test || true
